// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose.proto

package pt.ulisboa.tecnico.surething.pose;

/**
 * Protobuf type {@code pt.ulisboa.tecnico.surething.pose.HeaderMap}
 */
public final class HeaderMap extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pt.ulisboa.tecnico.surething.pose.HeaderMap)
    HeaderMapOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeaderMap.newBuilder() to construct.
  private HeaderMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeaderMap() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new HeaderMap();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HeaderMap(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              map_ = com.google.protobuf.MapField.newMapField(
                  MapDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<Integer, Value>
            map__ = input.readMessage(
                MapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            map_.getMutableMap().put(
                map__.getKey(), map__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pose.internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetMap();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pose.internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            HeaderMap.class, Builder.class);
  }

  public static final int MAP_FIELD_NUMBER = 1;
  private static final class MapDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        Integer, Value> defaultEntry =
            com.google.protobuf.MapEntry
            .<Integer, Value>newDefaultInstance(
                pose.internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_MapEntry_descriptor,
                com.google.protobuf.WireFormat.FieldType.INT32,
                0,
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                Value.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      Integer, Value> map_;
  private com.google.protobuf.MapField<Integer, Value>
  internalGetMap() {
    if (map_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MapDefaultEntryHolder.defaultEntry);
    }
    return map_;
  }

  public int getMapCount() {
    return internalGetMap().getMap().size();
  }
  /**
   * <pre>
   * map containing header parameters
   * will be serialized and put inside PoseEncrypt0
   * </pre>
   *
   * <code>map&lt;int32, .pt.ulisboa.tecnico.surething.pose.Value&gt; map = 1;</code>
   */

  @Override
  public boolean containsMap(
      int key) {
    
    return internalGetMap().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMapMap()} instead.
   */
  @Override
  @Deprecated
  public java.util.Map<Integer, Value> getMap() {
    return getMapMap();
  }
  /**
   * <pre>
   * map containing header parameters
   * will be serialized and put inside PoseEncrypt0
   * </pre>
   *
   * <code>map&lt;int32, .pt.ulisboa.tecnico.surething.pose.Value&gt; map = 1;</code>
   */
  @Override

  public java.util.Map<Integer, Value> getMapMap() {
    return internalGetMap().getMap();
  }
  /**
   * <pre>
   * map containing header parameters
   * will be serialized and put inside PoseEncrypt0
   * </pre>
   *
   * <code>map&lt;int32, .pt.ulisboa.tecnico.surething.pose.Value&gt; map = 1;</code>
   */
  @Override

  public Value getMapOrDefault(
      int key,
      Value defaultValue) {
    
    java.util.Map<Integer, Value> map =
        internalGetMap().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * map containing header parameters
   * will be serialized and put inside PoseEncrypt0
   * </pre>
   *
   * <code>map&lt;int32, .pt.ulisboa.tecnico.surething.pose.Value&gt; map = 1;</code>
   */
  @Override

  public Value getMapOrThrow(
      int key) {
    
    java.util.Map<Integer, Value> map =
        internalGetMap().getMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeIntegerMapTo(
        output,
        internalGetMap(),
        MapDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<Integer, Value> entry
         : internalGetMap().getMap().entrySet()) {
      com.google.protobuf.MapEntry<Integer, Value>
      map__ = MapDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, map__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof HeaderMap)) {
      return super.equals(obj);
    }
    HeaderMap other = (HeaderMap) obj;

    if (!internalGetMap().equals(
        other.internalGetMap())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetMap().getMap().isEmpty()) {
      hash = (37 * hash) + MAP_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMap().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static HeaderMap parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HeaderMap parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HeaderMap parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HeaderMap parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HeaderMap parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static HeaderMap parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static HeaderMap parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static HeaderMap parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static HeaderMap parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static HeaderMap parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static HeaderMap parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static HeaderMap parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(HeaderMap prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pt.ulisboa.tecnico.surething.pose.HeaderMap}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pt.ulisboa.tecnico.surething.pose.HeaderMap)
      HeaderMapOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pose.internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pose.internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HeaderMap.class, Builder.class);
    }

    // Construct using pt.ulisboa.tecnico.surething.pose.HeaderMap.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      internalGetMutableMap().clear();
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pose.internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_descriptor;
    }

    @Override
    public HeaderMap getDefaultInstanceForType() {
      return HeaderMap.getDefaultInstance();
    }

    @Override
    public HeaderMap build() {
      HeaderMap result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public HeaderMap buildPartial() {
      HeaderMap result = new HeaderMap(this);
      int from_bitField0_ = bitField0_;
      result.map_ = internalGetMap();
      result.map_.makeImmutable();
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof HeaderMap) {
        return mergeFrom((HeaderMap)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(HeaderMap other) {
      if (other == HeaderMap.getDefaultInstance()) return this;
      internalGetMutableMap().mergeFrom(
          other.internalGetMap());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      HeaderMap parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (HeaderMap) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        Integer, Value> map_;
    private com.google.protobuf.MapField<Integer, Value>
    internalGetMap() {
      if (map_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      return map_;
    }
    private com.google.protobuf.MapField<Integer, Value>
    internalGetMutableMap() {
      onChanged();;
      if (map_ == null) {
        map_ = com.google.protobuf.MapField.newMapField(
            MapDefaultEntryHolder.defaultEntry);
      }
      if (!map_.isMutable()) {
        map_ = map_.copy();
      }
      return map_;
    }

    public int getMapCount() {
      return internalGetMap().getMap().size();
    }
    /**
     * <pre>
     * map containing header parameters
     * will be serialized and put inside PoseEncrypt0
     * </pre>
     *
     * <code>map&lt;int32, .pt.ulisboa.tecnico.surething.pose.Value&gt; map = 1;</code>
     */

    @Override
    public boolean containsMap(
        int key) {
      
      return internalGetMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMapMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<Integer, Value> getMap() {
      return getMapMap();
    }
    /**
     * <pre>
     * map containing header parameters
     * will be serialized and put inside PoseEncrypt0
     * </pre>
     *
     * <code>map&lt;int32, .pt.ulisboa.tecnico.surething.pose.Value&gt; map = 1;</code>
     */
    @Override

    public java.util.Map<Integer, Value> getMapMap() {
      return internalGetMap().getMap();
    }
    /**
     * <pre>
     * map containing header parameters
     * will be serialized and put inside PoseEncrypt0
     * </pre>
     *
     * <code>map&lt;int32, .pt.ulisboa.tecnico.surething.pose.Value&gt; map = 1;</code>
     */
    @Override

    public Value getMapOrDefault(
        int key,
        Value defaultValue) {
      
      java.util.Map<Integer, Value> map =
          internalGetMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * map containing header parameters
     * will be serialized and put inside PoseEncrypt0
     * </pre>
     *
     * <code>map&lt;int32, .pt.ulisboa.tecnico.surething.pose.Value&gt; map = 1;</code>
     */
    @Override

    public Value getMapOrThrow(
        int key) {
      
      java.util.Map<Integer, Value> map =
          internalGetMap().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearMap() {
      internalGetMutableMap().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * map containing header parameters
     * will be serialized and put inside PoseEncrypt0
     * </pre>
     *
     * <code>map&lt;int32, .pt.ulisboa.tecnico.surething.pose.Value&gt; map = 1;</code>
     */

    public Builder removeMap(
        int key) {
      
      internalGetMutableMap().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @Deprecated
    public java.util.Map<Integer, Value>
    getMutableMap() {
      return internalGetMutableMap().getMutableMap();
    }
    /**
     * <pre>
     * map containing header parameters
     * will be serialized and put inside PoseEncrypt0
     * </pre>
     *
     * <code>map&lt;int32, .pt.ulisboa.tecnico.surething.pose.Value&gt; map = 1;</code>
     */
    public Builder putMap(
        int key,
        Value value) {
      
      if (value == null) { throw new NullPointerException(); }
      internalGetMutableMap().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * map containing header parameters
     * will be serialized and put inside PoseEncrypt0
     * </pre>
     *
     * <code>map&lt;int32, .pt.ulisboa.tecnico.surething.pose.Value&gt; map = 1;</code>
     */

    public Builder putAllMap(
        java.util.Map<Integer, Value> values) {
      internalGetMutableMap().getMutableMap()
          .putAll(values);
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pt.ulisboa.tecnico.surething.pose.HeaderMap)
  }

  // @@protoc_insertion_point(class_scope:pt.ulisboa.tecnico.surething.pose.HeaderMap)
  private static final HeaderMap DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new HeaderMap();
  }

  public static HeaderMap getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeaderMap>
      PARSER = new com.google.protobuf.AbstractParser<HeaderMap>() {
    @Override
    public HeaderMap parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HeaderMap(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HeaderMap> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<HeaderMap> getParserForType() {
    return PARSER;
  }

  @Override
  public HeaderMap getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

