// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose.proto

package pt.ulisboa.tecnico.surething.pose;

public interface HeaderMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.ulisboa.tecnico.surething.pose.HeaderMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * map containing header parameters
   * will be serialized and put inside PoseEncrypt0
   * </pre>
   *
   * <code>map&lt;int32, .pt.ulisboa.tecnico.surething.pose.Value&gt; map = 1;</code>
   */
  int getMapCount();
  /**
   * <pre>
   * map containing header parameters
   * will be serialized and put inside PoseEncrypt0
   * </pre>
   *
   * <code>map&lt;int32, .pt.ulisboa.tecnico.surething.pose.Value&gt; map = 1;</code>
   */
  boolean containsMap(
          int key);
  /**
   * Use {@link #getMapMap()} instead.
   */
  @Deprecated
  java.util.Map<Integer, Value>
  getMap();
  /**
   * <pre>
   * map containing header parameters
   * will be serialized and put inside PoseEncrypt0
   * </pre>
   *
   * <code>map&lt;int32, .pt.ulisboa.tecnico.surething.pose.Value&gt; map = 1;</code>
   */
  java.util.Map<Integer, Value>
  getMapMap();
  /**
   * <pre>
   * map containing header parameters
   * will be serialized and put inside PoseEncrypt0
   * </pre>
   *
   * <code>map&lt;int32, .pt.ulisboa.tecnico.surething.pose.Value&gt; map = 1;</code>
   */

  Value getMapOrDefault(
          int key,
          Value defaultValue);
  /**
   * <pre>
   * map containing header parameters
   * will be serialized and put inside PoseEncrypt0
   * </pre>
   *
   * <code>map&lt;int32, .pt.ulisboa.tecnico.surething.pose.Value&gt; map = 1;</code>
   */

  Value getMapOrThrow(
          int key);
}
