// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose.proto

package pt.ulisboa.tecnico.surething.pose;

public interface PoseEncrypt0OrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.ulisboa.tecnico.surething.pose.PoseEncrypt0)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *empty_or_serialized_map of HeaderMap type - string of bytes
   * </pre>
   *
   * <code>bytes protected = 1;</code>
   * @return The protected.
   */
  com.google.protobuf.ByteString getProtected();

  /**
   * <pre>
   *header map unprotected
   * </pre>
   *
   * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
   * @return Whether the unprotected field is set.
   */
  boolean hasUnprotected();
  /**
   * <pre>
   *header map unprotected
   * </pre>
   *
   * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
   * @return The unprotected.
   */
  HeaderMap getUnprotected();
  /**
   * <pre>
   *header map unprotected
   * </pre>
   *
   * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
   */
  HeaderMapOrBuilder getUnprotectedOrBuilder();

  /**
   * <pre>
   *ciphertext of payload - string of bytes
   * </pre>
   *
   * <code>bytes ciphertext = 3;</code>
   * @return The ciphertext.
   */
  com.google.protobuf.ByteString getCiphertext();
}
