// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose.proto

package pt.ulisboa.tecnico.surething.pose;

public final class pose {
  private pose() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_ulisboa_tecnico_surething_pose_PoseEncrypt0_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_ulisboa_tecnico_surething_pose_PoseEncrypt0_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_ulisboa_tecnico_surething_pose_Value_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_ulisboa_tecnico_surething_pose_Value_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_MapEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_MapEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_ulisboa_tecnico_surething_pose_Enc_Structure_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_ulisboa_tecnico_surething_pose_Enc_Structure_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_ulisboa_tecnico_surething_pose_Pose_Sign1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_ulisboa_tecnico_surething_pose_Pose_Sign1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pt_ulisboa_tecnico_surething_pose_Sig_Structure_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pt_ulisboa_tecnico_surething_pose_Sig_Structure_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\npose.proto\022!pt.ulisboa.tecnico.surethi" +
      "ng.pose\"x\n\014PoseEncrypt0\022\021\n\tprotected\030\001 \001" +
      "(\014\022A\n\013unprotected\030\002 \001(\0132,.pt.ulisboa.tec" +
      "nico.surething.pose.HeaderMap\022\022\n\nciphert" +
      "ext\030\003 \001(\014\"O\n\005Value\022\r\n\003int\030\001 \001(\005H\000\022\016\n\004tst" +
      "r\030\002 \001(\tH\000\022\016\n\004uint\030\003 \001(\rH\000\022\016\n\004bstr\030\004 \001(\014H" +
      "\000B\007\n\005Value\"\245\001\n\tHeaderMap\022B\n\003map\030\001 \003(\01325." +
      "pt.ulisboa.tecnico.surething.pose.Header" +
      "Map.MapEntry\032T\n\010MapEntry\022\013\n\003key\030\001 \001(\005\0227\n" +
      "\005value\030\002 \001(\0132(.pt.ulisboa.tecnico.sureth" +
      "ing.pose.Value:\0028\001\"r\n\rEnc_Structure\022\017\n\007c" +
      "ontext\030\001 \001(\t\022=\n\004body\030\002 \001(\0132/.pt.ulisboa." +
      "tecnico.surething.pose.PoseEncrypt0\022\021\n\tp" +
      "rotected\030\003 \001(\014\"\270\001\n\nPose_Sign1\022\021\n\tprotect" +
      "ed\030\001 \001(\014\022A\n\013unprotected\030\002 \001(\0132,.pt.ulisb" +
      "oa.tecnico.surething.pose.HeaderMap\022A\n\007p" +
      "ayload\030\003 \001(\01320.pt.ulisboa.tecnico.sureth" +
      "ing.pose.Enc_Structure\022\021\n\tsignature\030\004 \001(" +
      "\014\"u\n\rSig_Structure\022\017\n\007context\030\001 \001(\t\022;\n\004b" +
      "ody\030\002 \001(\0132-.pt.ulisboa.tecnico.surething" +
      ".pose.Pose_Sign1\022\026\n\016body_protected\030\003 \001(\014" +
      "B+\n!pt.ulisboa.tecnico.surething.poseB\004p" +
      "oseP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pt_ulisboa_tecnico_surething_pose_PoseEncrypt0_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pt_ulisboa_tecnico_surething_pose_PoseEncrypt0_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_ulisboa_tecnico_surething_pose_PoseEncrypt0_descriptor,
        new String[] { "Protected", "Unprotected", "Ciphertext", });
    internal_static_pt_ulisboa_tecnico_surething_pose_Value_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pt_ulisboa_tecnico_surething_pose_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_ulisboa_tecnico_surething_pose_Value_descriptor,
        new String[] { "Int", "Tstr", "Uint", "Bstr", "Value", });
    internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_descriptor,
        new String[] { "Map", });
    internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_MapEntry_descriptor =
      internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_descriptor.getNestedTypes().get(0);
    internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_ulisboa_tecnico_surething_pose_HeaderMap_MapEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_pt_ulisboa_tecnico_surething_pose_Enc_Structure_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pt_ulisboa_tecnico_surething_pose_Enc_Structure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_ulisboa_tecnico_surething_pose_Enc_Structure_descriptor,
        new String[] { "Context", "Body", "Protected", });
    internal_static_pt_ulisboa_tecnico_surething_pose_Pose_Sign1_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_pt_ulisboa_tecnico_surething_pose_Pose_Sign1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_ulisboa_tecnico_surething_pose_Pose_Sign1_descriptor,
        new String[] { "Protected", "Unprotected", "Payload", "Signature", });
    internal_static_pt_ulisboa_tecnico_surething_pose_Sig_Structure_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_pt_ulisboa_tecnico_surething_pose_Sig_Structure_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pt_ulisboa_tecnico_surething_pose_Sig_Structure_descriptor,
        new String[] { "Context", "Body", "BodyProtected", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
