// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose.proto

package pt.ulisboa.tecnico.surething.pose;

/**
 * <pre>
 *COSE_Sign1 - signature structure single signed
 * </pre>
 *
 * Protobuf type {@code pt.ulisboa.tecnico.surething.pose.Pose_Sign1}
 */
public final class Pose_Sign1 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pt.ulisboa.tecnico.surething.pose.Pose_Sign1)
    Pose_Sign1OrBuilder {
private static final long serialVersionUID = 0L;
  // Use Pose_Sign1.newBuilder() to construct.
  private Pose_Sign1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Pose_Sign1() {
    protected_ = com.google.protobuf.ByteString.EMPTY;
    signature_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Pose_Sign1();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Pose_Sign1(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {

            protected_ = input.readBytes();
            break;
          }
          case 18: {
            HeaderMap.Builder subBuilder = null;
            if (unprotected_ != null) {
              subBuilder = unprotected_.toBuilder();
            }
            unprotected_ = input.readMessage(HeaderMap.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(unprotected_);
              unprotected_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            Enc_Structure.Builder subBuilder = null;
            if (payload_ != null) {
              subBuilder = payload_.toBuilder();
            }
            payload_ = input.readMessage(Enc_Structure.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(payload_);
              payload_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {

            signature_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pose.internal_static_pt_ulisboa_tecnico_surething_pose_Pose_Sign1_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pose.internal_static_pt_ulisboa_tecnico_surething_pose_Pose_Sign1_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Pose_Sign1.class, Builder.class);
  }

  public static final int PROTECTED_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString protected_;
  /**
   * <pre>
   *empty_or_serialized_map of HeaderMap type - string of bytes
   * </pre>
   *
   * <code>bytes protected = 1;</code>
   * @return The protected.
   */
  @Override
  public com.google.protobuf.ByteString getProtected() {
    return protected_;
  }

  public static final int UNPROTECTED_FIELD_NUMBER = 2;
  private HeaderMap unprotected_;
  /**
   * <pre>
   *header map unprotected
   * </pre>
   *
   * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
   * @return Whether the unprotected field is set.
   */
  @Override
  public boolean hasUnprotected() {
    return unprotected_ != null;
  }
  /**
   * <pre>
   *header map unprotected
   * </pre>
   *
   * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
   * @return The unprotected.
   */
  @Override
  public HeaderMap getUnprotected() {
    return unprotected_ == null ? HeaderMap.getDefaultInstance() : unprotected_;
  }
  /**
   * <pre>
   *header map unprotected
   * </pre>
   *
   * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
   */
  @Override
  public HeaderMapOrBuilder getUnprotectedOrBuilder() {
    return getUnprotected();
  }

  public static final int PAYLOAD_FIELD_NUMBER = 3;
  private Enc_Structure payload_;
  /**
   * <pre>
   * instead of having plaintext payload, we have an encrypted structure
   * </pre>
   *
   * <code>.pt.ulisboa.tecnico.surething.pose.Enc_Structure payload = 3;</code>
   * @return Whether the payload field is set.
   */
  @Override
  public boolean hasPayload() {
    return payload_ != null;
  }
  /**
   * <pre>
   * instead of having plaintext payload, we have an encrypted structure
   * </pre>
   *
   * <code>.pt.ulisboa.tecnico.surething.pose.Enc_Structure payload = 3;</code>
   * @return The payload.
   */
  @Override
  public Enc_Structure getPayload() {
    return payload_ == null ? Enc_Structure.getDefaultInstance() : payload_;
  }
  /**
   * <pre>
   * instead of having plaintext payload, we have an encrypted structure
   * </pre>
   *
   * <code>.pt.ulisboa.tecnico.surething.pose.Enc_Structure payload = 3;</code>
   */
  @Override
  public Enc_StructureOrBuilder getPayloadOrBuilder() {
    return getPayload();
  }

  public static final int SIGNATURE_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString signature_;
  /**
   * <pre>
   * computed signature value of the payload
   * </pre>
   *
   * <code>bytes signature = 4;</code>
   * @return The signature.
   */
  @Override
  public com.google.protobuf.ByteString getSignature() {
    return signature_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!protected_.isEmpty()) {
      output.writeBytes(1, protected_);
    }
    if (unprotected_ != null) {
      output.writeMessage(2, getUnprotected());
    }
    if (payload_ != null) {
      output.writeMessage(3, getPayload());
    }
    if (!signature_.isEmpty()) {
      output.writeBytes(4, signature_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!protected_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, protected_);
    }
    if (unprotected_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUnprotected());
    }
    if (payload_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPayload());
    }
    if (!signature_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, signature_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Pose_Sign1)) {
      return super.equals(obj);
    }
    Pose_Sign1 other = (Pose_Sign1) obj;

    if (!getProtected()
        .equals(other.getProtected())) return false;
    if (hasUnprotected() != other.hasUnprotected()) return false;
    if (hasUnprotected()) {
      if (!getUnprotected()
          .equals(other.getUnprotected())) return false;
    }
    if (hasPayload() != other.hasPayload()) return false;
    if (hasPayload()) {
      if (!getPayload()
          .equals(other.getPayload())) return false;
    }
    if (!getSignature()
        .equals(other.getSignature())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROTECTED_FIELD_NUMBER;
    hash = (53 * hash) + getProtected().hashCode();
    if (hasUnprotected()) {
      hash = (37 * hash) + UNPROTECTED_FIELD_NUMBER;
      hash = (53 * hash) + getUnprotected().hashCode();
    }
    if (hasPayload()) {
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
    }
    hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
    hash = (53 * hash) + getSignature().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Pose_Sign1 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Pose_Sign1 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Pose_Sign1 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Pose_Sign1 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Pose_Sign1 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Pose_Sign1 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Pose_Sign1 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Pose_Sign1 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Pose_Sign1 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Pose_Sign1 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Pose_Sign1 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Pose_Sign1 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Pose_Sign1 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *COSE_Sign1 - signature structure single signed
   * </pre>
   *
   * Protobuf type {@code pt.ulisboa.tecnico.surething.pose.Pose_Sign1}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pt.ulisboa.tecnico.surething.pose.Pose_Sign1)
      Pose_Sign1OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pose.internal_static_pt_ulisboa_tecnico_surething_pose_Pose_Sign1_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pose.internal_static_pt_ulisboa_tecnico_surething_pose_Pose_Sign1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Pose_Sign1.class, Builder.class);
    }

    // Construct using pt.ulisboa.tecnico.surething.pose.Pose_Sign1.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      protected_ = com.google.protobuf.ByteString.EMPTY;

      if (unprotectedBuilder_ == null) {
        unprotected_ = null;
      } else {
        unprotected_ = null;
        unprotectedBuilder_ = null;
      }
      if (payloadBuilder_ == null) {
        payload_ = null;
      } else {
        payload_ = null;
        payloadBuilder_ = null;
      }
      signature_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pose.internal_static_pt_ulisboa_tecnico_surething_pose_Pose_Sign1_descriptor;
    }

    @Override
    public Pose_Sign1 getDefaultInstanceForType() {
      return Pose_Sign1.getDefaultInstance();
    }

    @Override
    public Pose_Sign1 build() {
      Pose_Sign1 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Pose_Sign1 buildPartial() {
      Pose_Sign1 result = new Pose_Sign1(this);
      result.protected_ = protected_;
      if (unprotectedBuilder_ == null) {
        result.unprotected_ = unprotected_;
      } else {
        result.unprotected_ = unprotectedBuilder_.build();
      }
      if (payloadBuilder_ == null) {
        result.payload_ = payload_;
      } else {
        result.payload_ = payloadBuilder_.build();
      }
      result.signature_ = signature_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Pose_Sign1) {
        return mergeFrom((Pose_Sign1)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Pose_Sign1 other) {
      if (other == Pose_Sign1.getDefaultInstance()) return this;
      if (other.getProtected() != com.google.protobuf.ByteString.EMPTY) {
        setProtected(other.getProtected());
      }
      if (other.hasUnprotected()) {
        mergeUnprotected(other.getUnprotected());
      }
      if (other.hasPayload()) {
        mergePayload(other.getPayload());
      }
      if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
        setSignature(other.getSignature());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Pose_Sign1 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Pose_Sign1) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.ByteString protected_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *empty_or_serialized_map of HeaderMap type - string of bytes
     * </pre>
     *
     * <code>bytes protected = 1;</code>
     * @return The protected.
     */
    @Override
    public com.google.protobuf.ByteString getProtected() {
      return protected_;
    }
    /**
     * <pre>
     *empty_or_serialized_map of HeaderMap type - string of bytes
     * </pre>
     *
     * <code>bytes protected = 1;</code>
     * @param value The protected to set.
     * @return This builder for chaining.
     */
    public Builder setProtected(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      protected_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *empty_or_serialized_map of HeaderMap type - string of bytes
     * </pre>
     *
     * <code>bytes protected = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtected() {
      
      protected_ = getDefaultInstance().getProtected();
      onChanged();
      return this;
    }

    private HeaderMap unprotected_;
    private com.google.protobuf.SingleFieldBuilderV3<
        HeaderMap, HeaderMap.Builder, HeaderMapOrBuilder> unprotectedBuilder_;
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     * @return Whether the unprotected field is set.
     */
    public boolean hasUnprotected() {
      return unprotectedBuilder_ != null || unprotected_ != null;
    }
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     * @return The unprotected.
     */
    public HeaderMap getUnprotected() {
      if (unprotectedBuilder_ == null) {
        return unprotected_ == null ? HeaderMap.getDefaultInstance() : unprotected_;
      } else {
        return unprotectedBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     */
    public Builder setUnprotected(HeaderMap value) {
      if (unprotectedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        unprotected_ = value;
        onChanged();
      } else {
        unprotectedBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     */
    public Builder setUnprotected(
        HeaderMap.Builder builderForValue) {
      if (unprotectedBuilder_ == null) {
        unprotected_ = builderForValue.build();
        onChanged();
      } else {
        unprotectedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     */
    public Builder mergeUnprotected(HeaderMap value) {
      if (unprotectedBuilder_ == null) {
        if (unprotected_ != null) {
          unprotected_ =
            HeaderMap.newBuilder(unprotected_).mergeFrom(value).buildPartial();
        } else {
          unprotected_ = value;
        }
        onChanged();
      } else {
        unprotectedBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     */
    public Builder clearUnprotected() {
      if (unprotectedBuilder_ == null) {
        unprotected_ = null;
        onChanged();
      } else {
        unprotected_ = null;
        unprotectedBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     */
    public HeaderMap.Builder getUnprotectedBuilder() {
      
      onChanged();
      return getUnprotectedFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     */
    public HeaderMapOrBuilder getUnprotectedOrBuilder() {
      if (unprotectedBuilder_ != null) {
        return unprotectedBuilder_.getMessageOrBuilder();
      } else {
        return unprotected_ == null ?
            HeaderMap.getDefaultInstance() : unprotected_;
      }
    }
    /**
     * <pre>
     *header map unprotected
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.HeaderMap unprotected = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        HeaderMap, HeaderMap.Builder, HeaderMapOrBuilder>
        getUnprotectedFieldBuilder() {
      if (unprotectedBuilder_ == null) {
        unprotectedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            HeaderMap, HeaderMap.Builder, HeaderMapOrBuilder>(
                getUnprotected(),
                getParentForChildren(),
                isClean());
        unprotected_ = null;
      }
      return unprotectedBuilder_;
    }

    private Enc_Structure payload_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Enc_Structure, Enc_Structure.Builder, Enc_StructureOrBuilder> payloadBuilder_;
    /**
     * <pre>
     * instead of having plaintext payload, we have an encrypted structure
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.Enc_Structure payload = 3;</code>
     * @return Whether the payload field is set.
     */
    public boolean hasPayload() {
      return payloadBuilder_ != null || payload_ != null;
    }
    /**
     * <pre>
     * instead of having plaintext payload, we have an encrypted structure
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.Enc_Structure payload = 3;</code>
     * @return The payload.
     */
    public Enc_Structure getPayload() {
      if (payloadBuilder_ == null) {
        return payload_ == null ? Enc_Structure.getDefaultInstance() : payload_;
      } else {
        return payloadBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * instead of having plaintext payload, we have an encrypted structure
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.Enc_Structure payload = 3;</code>
     */
    public Builder setPayload(Enc_Structure value) {
      if (payloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        payloadBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * instead of having plaintext payload, we have an encrypted structure
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.Enc_Structure payload = 3;</code>
     */
    public Builder setPayload(
        Enc_Structure.Builder builderForValue) {
      if (payloadBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        payloadBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * instead of having plaintext payload, we have an encrypted structure
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.Enc_Structure payload = 3;</code>
     */
    public Builder mergePayload(Enc_Structure value) {
      if (payloadBuilder_ == null) {
        if (payload_ != null) {
          payload_ =
            Enc_Structure.newBuilder(payload_).mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        payloadBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * instead of having plaintext payload, we have an encrypted structure
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.Enc_Structure payload = 3;</code>
     */
    public Builder clearPayload() {
      if (payloadBuilder_ == null) {
        payload_ = null;
        onChanged();
      } else {
        payload_ = null;
        payloadBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * instead of having plaintext payload, we have an encrypted structure
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.Enc_Structure payload = 3;</code>
     */
    public Enc_Structure.Builder getPayloadBuilder() {
      
      onChanged();
      return getPayloadFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * instead of having plaintext payload, we have an encrypted structure
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.Enc_Structure payload = 3;</code>
     */
    public Enc_StructureOrBuilder getPayloadOrBuilder() {
      if (payloadBuilder_ != null) {
        return payloadBuilder_.getMessageOrBuilder();
      } else {
        return payload_ == null ?
            Enc_Structure.getDefaultInstance() : payload_;
      }
    }
    /**
     * <pre>
     * instead of having plaintext payload, we have an encrypted structure
     * </pre>
     *
     * <code>.pt.ulisboa.tecnico.surething.pose.Enc_Structure payload = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Enc_Structure, Enc_Structure.Builder, Enc_StructureOrBuilder>
        getPayloadFieldBuilder() {
      if (payloadBuilder_ == null) {
        payloadBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Enc_Structure, Enc_Structure.Builder, Enc_StructureOrBuilder>(
                getPayload(),
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      return payloadBuilder_;
    }

    private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * computed signature value of the payload
     * </pre>
     *
     * <code>bytes signature = 4;</code>
     * @return The signature.
     */
    @Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }
    /**
     * <pre>
     * computed signature value of the payload
     * </pre>
     *
     * <code>bytes signature = 4;</code>
     * @param value The signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignature(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      signature_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * computed signature value of the payload
     * </pre>
     *
     * <code>bytes signature = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignature() {
      
      signature_ = getDefaultInstance().getSignature();
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pt.ulisboa.tecnico.surething.pose.Pose_Sign1)
  }

  // @@protoc_insertion_point(class_scope:pt.ulisboa.tecnico.surething.pose.Pose_Sign1)
  private static final Pose_Sign1 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Pose_Sign1();
  }

  public static Pose_Sign1 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Pose_Sign1>
      PARSER = new com.google.protobuf.AbstractParser<Pose_Sign1>() {
    @Override
    public Pose_Sign1 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Pose_Sign1(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Pose_Sign1> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Pose_Sign1> getParserForType() {
    return PARSER;
  }

  @Override
  public Pose_Sign1 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

