// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose.proto

package pt.ulisboa.tecnico.surething.pose;

/**
 * <pre>
 * Canonical form of a well-defined byte stream
 * </pre>
 *
 * Protobuf type {@code pt.ulisboa.tecnico.surething.pose.Sig_Structure}
 */
public final class Sig_Structure extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pt.ulisboa.tecnico.surething.pose.Sig_Structure)
    Sig_StructureOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Sig_Structure.newBuilder() to construct.
  private Sig_Structure(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Sig_Structure() {
    context_ = "";
    bodyProtected_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Sig_Structure();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Sig_Structure(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            context_ = s;
            break;
          }
          case 18: {
            Pose_Sign1.Builder subBuilder = null;
            if (body_ != null) {
              subBuilder = body_.toBuilder();
            }
            body_ = input.readMessage(Pose_Sign1.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(body_);
              body_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {

            bodyProtected_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return pose.internal_static_pt_ulisboa_tecnico_surething_pose_Sig_Structure_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return pose.internal_static_pt_ulisboa_tecnico_surething_pose_Sig_Structure_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Sig_Structure.class, Builder.class);
  }

  public static final int CONTEXT_FIELD_NUMBER = 1;
  private volatile Object context_;
  /**
   * <code>string context = 1;</code>
   * @return The context.
   */
  @Override
  public String getContext() {
    Object ref = context_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      context_ = s;
      return s;
    }
  }
  /**
   * <code>string context = 1;</code>
   * @return The bytes for context.
   */
  @Override
  public com.google.protobuf.ByteString
      getContextBytes() {
    Object ref = context_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      context_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODY_FIELD_NUMBER = 2;
  private Pose_Sign1 body_;
  /**
   * <code>.pt.ulisboa.tecnico.surething.pose.Pose_Sign1 body = 2;</code>
   * @return Whether the body field is set.
   */
  @Override
  public boolean hasBody() {
    return body_ != null;
  }
  /**
   * <code>.pt.ulisboa.tecnico.surething.pose.Pose_Sign1 body = 2;</code>
   * @return The body.
   */
  @Override
  public Pose_Sign1 getBody() {
    return body_ == null ? Pose_Sign1.getDefaultInstance() : body_;
  }
  /**
   * <code>.pt.ulisboa.tecnico.surething.pose.Pose_Sign1 body = 2;</code>
   */
  @Override
  public Pose_Sign1OrBuilder getBodyOrBuilder() {
    return getBody();
  }

  public static final int BODY_PROTECTED_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString bodyProtected_;
  /**
   * <pre>
   * protected fields of the body
   * </pre>
   *
   * <code>bytes body_protected = 3;</code>
   * @return The bodyProtected.
   */
  @Override
  public com.google.protobuf.ByteString getBodyProtected() {
    return bodyProtected_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getContextBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, context_);
    }
    if (body_ != null) {
      output.writeMessage(2, getBody());
    }
    if (!bodyProtected_.isEmpty()) {
      output.writeBytes(3, bodyProtected_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getContextBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, context_);
    }
    if (body_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBody());
    }
    if (!bodyProtected_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, bodyProtected_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Sig_Structure)) {
      return super.equals(obj);
    }
    Sig_Structure other = (Sig_Structure) obj;

    if (!getContext()
        .equals(other.getContext())) return false;
    if (hasBody() != other.hasBody()) return false;
    if (hasBody()) {
      if (!getBody()
          .equals(other.getBody())) return false;
    }
    if (!getBodyProtected()
        .equals(other.getBodyProtected())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
    hash = (53 * hash) + getContext().hashCode();
    if (hasBody()) {
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
    }
    hash = (37 * hash) + BODY_PROTECTED_FIELD_NUMBER;
    hash = (53 * hash) + getBodyProtected().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Sig_Structure parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Sig_Structure parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Sig_Structure parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Sig_Structure parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Sig_Structure parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Sig_Structure parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Sig_Structure parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Sig_Structure parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Sig_Structure parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Sig_Structure parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Sig_Structure parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Sig_Structure parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Sig_Structure prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Canonical form of a well-defined byte stream
   * </pre>
   *
   * Protobuf type {@code pt.ulisboa.tecnico.surething.pose.Sig_Structure}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pt.ulisboa.tecnico.surething.pose.Sig_Structure)
      Sig_StructureOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pose.internal_static_pt_ulisboa_tecnico_surething_pose_Sig_Structure_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pose.internal_static_pt_ulisboa_tecnico_surething_pose_Sig_Structure_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Sig_Structure.class, Builder.class);
    }

    // Construct using pt.ulisboa.tecnico.surething.pose.Sig_Structure.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      context_ = "";

      if (bodyBuilder_ == null) {
        body_ = null;
      } else {
        body_ = null;
        bodyBuilder_ = null;
      }
      bodyProtected_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return pose.internal_static_pt_ulisboa_tecnico_surething_pose_Sig_Structure_descriptor;
    }

    @Override
    public Sig_Structure getDefaultInstanceForType() {
      return Sig_Structure.getDefaultInstance();
    }

    @Override
    public Sig_Structure build() {
      Sig_Structure result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Sig_Structure buildPartial() {
      Sig_Structure result = new Sig_Structure(this);
      result.context_ = context_;
      if (bodyBuilder_ == null) {
        result.body_ = body_;
      } else {
        result.body_ = bodyBuilder_.build();
      }
      result.bodyProtected_ = bodyProtected_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Sig_Structure) {
        return mergeFrom((Sig_Structure)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Sig_Structure other) {
      if (other == Sig_Structure.getDefaultInstance()) return this;
      if (!other.getContext().isEmpty()) {
        context_ = other.context_;
        onChanged();
      }
      if (other.hasBody()) {
        mergeBody(other.getBody());
      }
      if (other.getBodyProtected() != com.google.protobuf.ByteString.EMPTY) {
        setBodyProtected(other.getBodyProtected());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Sig_Structure parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Sig_Structure) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object context_ = "";
    /**
     * <code>string context = 1;</code>
     * @return The context.
     */
    public String getContext() {
      Object ref = context_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        context_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string context = 1;</code>
     * @return The bytes for context.
     */
    public com.google.protobuf.ByteString
        getContextBytes() {
      Object ref = context_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        context_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string context = 1;</code>
     * @param value The context to set.
     * @return This builder for chaining.
     */
    public Builder setContext(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      context_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string context = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContext() {
      
      context_ = getDefaultInstance().getContext();
      onChanged();
      return this;
    }
    /**
     * <code>string context = 1;</code>
     * @param value The bytes for context to set.
     * @return This builder for chaining.
     */
    public Builder setContextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      context_ = value;
      onChanged();
      return this;
    }

    private Pose_Sign1 body_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Pose_Sign1, Pose_Sign1.Builder, Pose_Sign1OrBuilder> bodyBuilder_;
    /**
     * <code>.pt.ulisboa.tecnico.surething.pose.Pose_Sign1 body = 2;</code>
     * @return Whether the body field is set.
     */
    public boolean hasBody() {
      return bodyBuilder_ != null || body_ != null;
    }
    /**
     * <code>.pt.ulisboa.tecnico.surething.pose.Pose_Sign1 body = 2;</code>
     * @return The body.
     */
    public Pose_Sign1 getBody() {
      if (bodyBuilder_ == null) {
        return body_ == null ? Pose_Sign1.getDefaultInstance() : body_;
      } else {
        return bodyBuilder_.getMessage();
      }
    }
    /**
     * <code>.pt.ulisboa.tecnico.surething.pose.Pose_Sign1 body = 2;</code>
     */
    public Builder setBody(Pose_Sign1 value) {
      if (bodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        bodyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.pt.ulisboa.tecnico.surething.pose.Pose_Sign1 body = 2;</code>
     */
    public Builder setBody(
        Pose_Sign1.Builder builderForValue) {
      if (bodyBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        bodyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.pt.ulisboa.tecnico.surething.pose.Pose_Sign1 body = 2;</code>
     */
    public Builder mergeBody(Pose_Sign1 value) {
      if (bodyBuilder_ == null) {
        if (body_ != null) {
          body_ =
            Pose_Sign1.newBuilder(body_).mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        bodyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.pt.ulisboa.tecnico.surething.pose.Pose_Sign1 body = 2;</code>
     */
    public Builder clearBody() {
      if (bodyBuilder_ == null) {
        body_ = null;
        onChanged();
      } else {
        body_ = null;
        bodyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.pt.ulisboa.tecnico.surething.pose.Pose_Sign1 body = 2;</code>
     */
    public Pose_Sign1.Builder getBodyBuilder() {
      
      onChanged();
      return getBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.pt.ulisboa.tecnico.surething.pose.Pose_Sign1 body = 2;</code>
     */
    public Pose_Sign1OrBuilder getBodyOrBuilder() {
      if (bodyBuilder_ != null) {
        return bodyBuilder_.getMessageOrBuilder();
      } else {
        return body_ == null ?
            Pose_Sign1.getDefaultInstance() : body_;
      }
    }
    /**
     * <code>.pt.ulisboa.tecnico.surething.pose.Pose_Sign1 body = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Pose_Sign1, Pose_Sign1.Builder, Pose_Sign1OrBuilder>
        getBodyFieldBuilder() {
      if (bodyBuilder_ == null) {
        bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Pose_Sign1, Pose_Sign1.Builder, Pose_Sign1OrBuilder>(
                getBody(),
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      return bodyBuilder_;
    }

    private com.google.protobuf.ByteString bodyProtected_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * protected fields of the body
     * </pre>
     *
     * <code>bytes body_protected = 3;</code>
     * @return The bodyProtected.
     */
    @Override
    public com.google.protobuf.ByteString getBodyProtected() {
      return bodyProtected_;
    }
    /**
     * <pre>
     * protected fields of the body
     * </pre>
     *
     * <code>bytes body_protected = 3;</code>
     * @param value The bodyProtected to set.
     * @return This builder for chaining.
     */
    public Builder setBodyProtected(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bodyProtected_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * protected fields of the body
     * </pre>
     *
     * <code>bytes body_protected = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBodyProtected() {
      
      bodyProtected_ = getDefaultInstance().getBodyProtected();
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pt.ulisboa.tecnico.surething.pose.Sig_Structure)
  }

  // @@protoc_insertion_point(class_scope:pt.ulisboa.tecnico.surething.pose.Sig_Structure)
  private static final Sig_Structure DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Sig_Structure();
  }

  public static Sig_Structure getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Sig_Structure>
      PARSER = new com.google.protobuf.AbstractParser<Sig_Structure>() {
    @Override
    public Sig_Structure parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Sig_Structure(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Sig_Structure> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Sig_Structure> getParserForType() {
    return PARSER;
  }

  @Override
  public Sig_Structure getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

