// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose.proto

package pt.ulisboa.tecnico.surething.pose;

public interface Sig_StructureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pt.ulisboa.tecnico.surething.pose.Sig_Structure)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string context = 1;</code>
   * @return The context.
   */
  String getContext();
  /**
   * <code>string context = 1;</code>
   * @return The bytes for context.
   */
  com.google.protobuf.ByteString
      getContextBytes();

  /**
   * <code>.pt.ulisboa.tecnico.surething.pose.Pose_Sign1 body = 2;</code>
   * @return Whether the body field is set.
   */
  boolean hasBody();
  /**
   * <code>.pt.ulisboa.tecnico.surething.pose.Pose_Sign1 body = 2;</code>
   * @return The body.
   */
  Pose_Sign1 getBody();
  /**
   * <code>.pt.ulisboa.tecnico.surething.pose.Pose_Sign1 body = 2;</code>
   */
  Pose_Sign1OrBuilder getBodyOrBuilder();

  /**
   * <pre>
   * protected fields of the body
   * </pre>
   *
   * <code>bytes body_protected = 3;</code>
   * @return The bodyProtected.
   */
  com.google.protobuf.ByteString getBodyProtected();
}
